name: flutter_card_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/ava.jpeg
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf
